---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _layouts
  label: Layouts
  create: documents
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: _includes
  label: Includes
  create: all
  match: "**/*"
  new_doc_ext: ".html"
upload_dir: ''
public_path: https://res.cloudinary.com/dznhn4oax/image/upload
front_matter_path: https://res.cloudinary.com/dznhn4oax/image/upload/c_fit
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
